
title: Computational Playground
author:
  name: Biplab P
  email: biplabp@iisc.ac.in
description: Surfing the solution space ğŸ„
url: https://12345pnp.github.io/comp-play/
show_excerpts: false # set to true to show excerpts on the homepage

twitter_username: 12345pnp
github_username:  12345pnp

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
