
title: Computational Playground
description: Surfing the solution space ğŸ„
url: https://12345pnp.github.io/comp-play/
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: 12345pnp
    github:  12345pnp

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
